/// Die deutschen Ländernamen.
///
/// **Warum es sie geben muss.** Der Länderkatalog kommt aus
/// `countryInfo.txt` von GeoNames, und der führt jedes Land nur
/// **englisch**. In der deutschen Oberfläche stand deshalb „Germany",
/// „Poland", „Switzerland" – in der Länderliste, in den Suchfiltern, auf
/// dem Infoblatt jeder Aufnahme. An der gewachsenen Bibliothek waren das
/// alle fünf vorkommenden Länder.
///
/// **Woher die Namen stammen.** Aus CLDR, dem Datensatz, aus dem auch
/// Betriebssysteme ihre Ländernamen nehmen (`Intl.DisplayNames`, Locale
/// `de`), einmal für alle 252 Einträge der Datei erzeugt und hier
/// abgelegt. Nicht von Hand geschrieben: „Kongo-Kinshasa" und
/// „St. Vincent und die Grenadinen" sind genau die Stellen, an denen eine
/// selbstgemachte Liste danebengreift.
///
/// **Nachgeschlagen wird über den ISO-Code, nicht über den englischen
/// Namen.** Benennt GeoNames morgen ein Land um, ändert das hier nichts.
///
/// Von den Einträgen sind 97 mit dem englischen Namen identisch (Andorra,
/// Malta, Panama …). Sie stehen trotzdem hier – eine Liste, die nur die
/// Unterschiede führt, macht aus jedem fehlenden Eintrag die stille Frage,
/// ob er vergessen wurde oder gleich ist.
///
/// **Zwei Einträge fehlen mit Absicht.** GeoNames führt noch die
/// aufgelösten Codes `AN` (Niederländische Antillen) und `CS` (Serbien und
/// Montenegro); CLDR beantwortet beide mit ihrem Nachfolger und machte
/// daraus „Curaçao" und „Serbien" – zwei Länder, die dann zweimal in der
/// Liste stünden, eines davon unter falschem Namen. Für sie bleibt es beim
/// englischen Namen aus dem Katalog, und der ist der richtige.
library;

/// ISO-Code (grossgeschrieben) auf den deutschen Namen.
const laendernamenDe = <String, String>{
  'AD': 'Andorra',
  'AE': 'Vereinigte Arabische Emirate',
  'AF': 'Afghanistan',
  'AG': 'Antigua und Barbuda',
  'AI': 'Anguilla',
  'AL': 'Albanien',
  'AM': 'Armenien',
  'AO': 'Angola',
  'AQ': 'Antarktis',
  'AR': 'Argentinien',
  'AS': 'Amerikanisch-Samoa',
  'AT': 'Österreich',
  'AU': 'Australien',
  'AW': 'Aruba',
  'AX': 'Ålandinseln',
  'AZ': 'Aserbaidschan',
  'BA': 'Bosnien und Herzegowina',
  'BB': 'Barbados',
  'BD': 'Bangladesch',
  'BE': 'Belgien',
  'BF': 'Burkina Faso',
  'BG': 'Bulgarien',
  'BH': 'Bahrain',
  'BI': 'Burundi',
  'BJ': 'Benin',
  'BL': 'St. Barthélemy',
  'BM': 'Bermuda',
  'BN': 'Brunei Darussalam',
  'BO': 'Bolivien',
  'BQ': 'Karibische Niederlande',
  'BR': 'Brasilien',
  'BS': 'Bahamas',
  'BT': 'Bhutan',
  'BV': 'Bouvetinsel',
  'BW': 'Botsuana',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'CA': 'Kanada',
  'CC': 'Kokosinseln',
  'CD': 'Kongo-Kinshasa',
  'CF': 'Zentralafrikanische Republik',
  'CG': 'Kongo-Brazzaville',
  'CH': 'Schweiz',
  'CI': 'Côte d’Ivoire',
  'CK': 'Cookinseln',
  'CL': 'Chile',
  'CM': 'Kamerun',
  'CN': 'China, Festland',
  'CO': 'Kolumbien',
  'CR': 'Costa Rica',
  'CU': 'Kuba',
  'CV': 'Cabo Verde',
  'CW': 'Curaçao',
  'CX': 'Weihnachtsinsel',
  'CY': 'Zypern',
  'CZ': 'Tschechien',
  'DE': 'Deutschland',
  'DJ': 'Dschibuti',
  'DK': 'Dänemark',
  'DM': 'Dominica',
  'DO': 'Dominikanische Republik',
  'DZ': 'Algerien',
  'EC': 'Ecuador',
  'EE': 'Estland',
  'EG': 'Ägypten',
  'EH': 'Westsahara',
  'ER': 'Eritrea',
  'ES': 'Spanien',
  'ET': 'Äthiopien',
  'FI': 'Finnland',
  'FJ': 'Fidschi',
  'FK': 'Falklandinseln',
  'FM': 'Mikronesien',
  'FO': 'Färöer',
  'FR': 'Frankreich',
  'GA': 'Gabun',
  'GB': 'Vereinigtes Königreich',
  'GD': 'Grenada',
  'GE': 'Georgien',
  'GF': 'Französisch-Guayana',
  'GG': 'Guernsey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Grönland',
  'GM': 'Gambia',
  'GN': 'Guinea',
  'GP': 'Guadeloupe',
  'GQ': 'Äquatorialguinea',
  'GR': 'Griechenland',
  'GS': 'Südgeorgien und die Südlichen Sandwichinseln',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HK': 'Hongkong',
  'HM': 'Heard und McDonaldinseln',
  'HN': 'Honduras',
  'HR': 'Kroatien',
  'HT': 'Haiti',
  'HU': 'Ungarn',
  'ID': 'Indonesien',
  'IE': 'Irland',
  'IL': 'Israel',
  'IM': 'Isle of Man',
  'IN': 'Indien',
  'IO': 'Chagos-Archipel',
  'IQ': 'Irak',
  'IR': 'Iran',
  'IS': 'Island',
  'IT': 'Italien',
  'JE': 'Jersey',
  'JM': 'Jamaika',
  'JO': 'Jordanien',
  'JP': 'Japan',
  'KE': 'Kenia',
  'KG': 'Kirgisistan',
  'KH': 'Kambodscha',
  'KI': 'Kiribati',
  'KM': 'Komoren',
  'KN': 'St. Kitts und Nevis',
  'KP': 'Nordkorea',
  'KR': 'Südkorea',
  'KW': 'Kuwait',
  'KY': 'Kaimaninseln',
  'KZ': 'Kasachstan',
  'LA': 'Laos',
  'LB': 'Libanon',
  'LC': 'St. Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LR': 'Liberia',
  'LS': 'Lesotho',
  'LT': 'Litauen',
  'LU': 'Luxemburg',
  'LV': 'Lettland',
  'LY': 'Libyen',
  'MA': 'Marokko',
  'MC': 'Monaco',
  'MD': 'Republik Moldau',
  'ME': 'Montenegro',
  'MF': 'St. Martin',
  'MG': 'Madagaskar',
  'MH': 'Marshallinseln',
  'MK': 'Nordmazedonien',
  'ML': 'Mali',
  'MM': 'Myanmar',
  'MN': 'Mongolei',
  'MO': 'Macao',
  'MP': 'Nördliche Marianen',
  'MQ': 'Martinique',
  'MR': 'Mauretanien',
  'MS': 'Montserrat',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Malediven',
  'MW': 'Malawi',
  'MX': 'Mexiko',
  'MY': 'Malaysia',
  'MZ': 'Mosambik',
  'NA': 'Namibia',
  'NC': 'Neukaledonien',
  'NE': 'Niger',
  'NF': 'Norfolkinsel',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Niederlande',
  'NO': 'Norwegen',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NU': 'Niue',
  'NZ': 'Neuseeland',
  'OM': 'Oman',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'Französisch-Polynesien',
  'PG': 'Papua-Neuguinea',
  'PH': 'Philippinen',
  'PK': 'Pakistan',
  'PL': 'Polen',
  'PM': 'St. Pierre und Miquelon',
  'PN': 'Pitcairninseln',
  'PR': 'Puerto Rico',
  'PS': 'Palästinensische Autonomiegebiete',
  'PT': 'Portugal',
  'PW': 'Palau',
  'PY': 'Paraguay',
  'QA': 'Katar',
  'RE': 'Réunion',
  'RO': 'Rumänien',
  'RS': 'Serbien',
  'RU': 'Russland',
  'RW': 'Ruanda',
  'SA': 'Saudi-Arabien',
  'SB': 'Salomonen',
  'SC': 'Seychellen',
  'SD': 'Sudan',
  'SE': 'Schweden',
  'SG': 'Singapur',
  'SH': 'St. Helena',
  'SI': 'Slowenien',
  'SJ': 'Spitzbergen und Jan Mayen',
  'SK': 'Slowakei',
  'SL': 'Sierra Leone',
  'SM': 'San Marino',
  'SN': 'Senegal',
  'SO': 'Somalia',
  'SR': 'Suriname',
  'SS': 'Südsudan',
  'ST': 'São Tomé und Príncipe',
  'SV': 'El Salvador',
  'SX': 'Sint Maarten',
  'SY': 'Syrien',
  'SZ': 'Eswatini',
  'TC': 'Turks- und Caicosinseln',
  'TD': 'Tschad',
  'TF': 'Französische Süd- und Antarktisgebiete',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tadschikistan',
  'TK': 'Tokelau',
  'TL': 'Timor-Leste',
  'TM': 'Turkmenistan',
  'TN': 'Tunesien',
  'TO': 'Tonga',
  'TR': 'Türkei',
  'TT': 'Trinidad und Tobago',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tansania',
  'UA': 'Ukraine',
  'UG': 'Uganda',
  'UM': 'Amerikanische Überseeinseln',
  'US': 'Vereinigte Staaten',
  'UY': 'Uruguay',
  'UZ': 'Usbekistan',
  'VA': 'Vatikanstadt',
  'VC': 'St. Vincent und die Grenadinen',
  'VE': 'Venezuela',
  'VG': 'Britische Jungferninseln',
  'VI': 'Amerikanische Jungferninseln',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'Wallis und Futuna',
  'WS': 'Samoa',
  'XK': 'Kosovo',
  'YE': 'Jemen',
  'YT': 'Mayotte',
  'ZA': 'Südafrika',
  'ZM': 'Sambia',
  'ZW': 'Simbabwe',
};

/// Der Ländername in der Sprache der Oberfläche.
///
/// [englisch] ist der Name aus dem Katalog und bleibt die Antwort, wenn
/// die Sprache nicht Deutsch ist oder der Code unbekannt – ein englischer
/// Name ist immer noch besser als ein leeres Feld oder ein blosses Kürzel.
String landesname(String iso, String englisch, String sprache) {
  if (!sprache.startsWith('de')) return englisch;
  return laendernamenDe[iso.toUpperCase()] ?? englisch;
}


/// Dieselben Namen, aber nachgeschlagen über den **englischen** Namen.
///
/// Denn das ist, was in den Aufnahmen steht: Die Umkehr-Geokodierung
/// schreibt `location_country` als ausgeschriebenen englischen Namen aus
/// `countryInfo.txt`, nicht als Code. Ohne diesen zweiten Weg bliebe jede
/// Anzeige, die von einer Aufnahme ausgeht, englisch – das Infoblatt, die
/// Ortszeile, die Ortsgruppen der Übersicht.
///
/// Nur die Einträge, bei denen sich der Name unterscheidet. Hier ist das
/// richtig herum: Ein fehlender Eintrag heisst „der englische Name ist
/// auch der deutsche", und genau das soll dann herauskommen.
const _laendernamenDeNachEnglisch = <String, String>{
  'United Arab Emirates': 'Vereinigte Arabische Emirate',
  'Antigua and Barbuda': 'Antigua und Barbuda',
  'Albania': 'Albanien',
  'Armenia': 'Armenien',
  'Antarctica': 'Antarktis',
  'Argentina': 'Argentinien',
  'American Samoa': 'Amerikanisch-Samoa',
  'Austria': 'Österreich',
  'Australia': 'Australien',
  'Aland Islands': 'Ålandinseln',
  'Azerbaijan': 'Aserbaidschan',
  'Bosnia and Herzegovina': 'Bosnien und Herzegowina',
  'Bangladesh': 'Bangladesch',
  'Belgium': 'Belgien',
  'Bulgaria': 'Bulgarien',
  'Saint Barthelemy': 'St. Barthélemy',
  'Brunei': 'Brunei Darussalam',
  'Bolivia': 'Bolivien',
  'Bonaire, Saint Eustatius and Saba ': 'Karibische Niederlande',
  'Brazil': 'Brasilien',
  'Bouvet Island': 'Bouvetinsel',
  'Botswana': 'Botsuana',
  'Canada': 'Kanada',
  'Cocos Islands': 'Kokosinseln',
  'Democratic Republic of the Congo': 'Kongo-Kinshasa',
  'Central African Republic': 'Zentralafrikanische Republik',
  'Republic of the Congo': 'Kongo-Brazzaville',
  'Switzerland': 'Schweiz',
  'Ivory Coast': 'Côte d’Ivoire',
  'Cook Islands': 'Cookinseln',
  'Cameroon': 'Kamerun',
  'China': 'China, Festland',
  'Colombia': 'Kolumbien',
  'Cuba': 'Kuba',
  'Curacao': 'Curaçao',
  'Christmas Island': 'Weihnachtsinsel',
  'Cyprus': 'Zypern',
  'Czechia': 'Tschechien',
  'Germany': 'Deutschland',
  'Djibouti': 'Dschibuti',
  'Denmark': 'Dänemark',
  'Dominican Republic': 'Dominikanische Republik',
  'Algeria': 'Algerien',
  'Estonia': 'Estland',
  'Egypt': 'Ägypten',
  'Western Sahara': 'Westsahara',
  'Spain': 'Spanien',
  'Ethiopia': 'Äthiopien',
  'Finland': 'Finnland',
  'Fiji': 'Fidschi',
  'Falkland Islands': 'Falklandinseln',
  'Micronesia': 'Mikronesien',
  'Faroe Islands': 'Färöer',
  'France': 'Frankreich',
  'Gabon': 'Gabun',
  'United Kingdom': 'Vereinigtes Königreich',
  'Georgia': 'Georgien',
  'French Guiana': 'Französisch-Guayana',
  'Greenland': 'Grönland',
  'Equatorial Guinea': 'Äquatorialguinea',
  'Greece': 'Griechenland',
  'South Georgia and the South Sandwich Islands': 'Südgeorgien und die Südlichen Sandwichinseln',
  'Hong Kong': 'Hongkong',
  'Heard Island and McDonald Islands': 'Heard und McDonaldinseln',
  'Croatia': 'Kroatien',
  'Hungary': 'Ungarn',
  'Indonesia': 'Indonesien',
  'Ireland': 'Irland',
  'India': 'Indien',
  'British Indian Ocean Territory': 'Chagos-Archipel',
  'Iraq': 'Irak',
  'Iceland': 'Island',
  'Italy': 'Italien',
  'Jamaica': 'Jamaika',
  'Jordan': 'Jordanien',
  'Kenya': 'Kenia',
  'Kyrgyzstan': 'Kirgisistan',
  'Cambodia': 'Kambodscha',
  'Comoros': 'Komoren',
  'Saint Kitts and Nevis': 'St. Kitts und Nevis',
  'North Korea': 'Nordkorea',
  'South Korea': 'Südkorea',
  'Cayman Islands': 'Kaimaninseln',
  'Kazakhstan': 'Kasachstan',
  'Lebanon': 'Libanon',
  'Saint Lucia': 'St. Lucia',
  'Lithuania': 'Litauen',
  'Luxembourg': 'Luxemburg',
  'Latvia': 'Lettland',
  'Libya': 'Libyen',
  'Morocco': 'Marokko',
  'Moldova': 'Republik Moldau',
  'Saint Martin': 'St. Martin',
  'Madagascar': 'Madagaskar',
  'Marshall Islands': 'Marshallinseln',
  'North Macedonia': 'Nordmazedonien',
  'Mongolia': 'Mongolei',
  'Northern Mariana Islands': 'Nördliche Marianen',
  'Mauritania': 'Mauretanien',
  'Maldives': 'Malediven',
  'Mexico': 'Mexiko',
  'Mozambique': 'Mosambik',
  'New Caledonia': 'Neukaledonien',
  'Norfolk Island': 'Norfolkinsel',
  'The Netherlands': 'Niederlande',
  'Norway': 'Norwegen',
  'New Zealand': 'Neuseeland',
  'French Polynesia': 'Französisch-Polynesien',
  'Papua New Guinea': 'Papua-Neuguinea',
  'Philippines': 'Philippinen',
  'Poland': 'Polen',
  'Saint Pierre and Miquelon': 'St. Pierre und Miquelon',
  'Pitcairn': 'Pitcairninseln',
  'Palestinian Territory': 'Palästinensische Autonomiegebiete',
  'Qatar': 'Katar',
  'Reunion': 'Réunion',
  'Romania': 'Rumänien',
  'Serbia': 'Serbien',
  'Russia': 'Russland',
  'Rwanda': 'Ruanda',
  'Saudi Arabia': 'Saudi-Arabien',
  'Solomon Islands': 'Salomonen',
  'Seychelles': 'Seychellen',
  'Sweden': 'Schweden',
  'Singapore': 'Singapur',
  'Saint Helena': 'St. Helena',
  'Slovenia': 'Slowenien',
  'Svalbard and Jan Mayen': 'Spitzbergen und Jan Mayen',
  'Slovakia': 'Slowakei',
  'South Sudan': 'Südsudan',
  'Sao Tome and Principe': 'São Tomé und Príncipe',
  'Syria': 'Syrien',
  'Turks and Caicos Islands': 'Turks- und Caicosinseln',
  'Chad': 'Tschad',
  'French Southern Territories': 'Französische Süd- und Antarktisgebiete',
  'Tajikistan': 'Tadschikistan',
  'Timor Leste': 'Timor-Leste',
  'Tunisia': 'Tunesien',
  'Turkey': 'Türkei',
  'Trinidad and Tobago': 'Trinidad und Tobago',
  'Tanzania': 'Tansania',
  'United States Minor Outlying Islands': 'Amerikanische Überseeinseln',
  'United States': 'Vereinigte Staaten',
  'Uzbekistan': 'Usbekistan',
  'Vatican': 'Vatikanstadt',
  'Saint Vincent and the Grenadines': 'St. Vincent und die Grenadinen',
  'British Virgin Islands': 'Britische Jungferninseln',
  'U.S. Virgin Islands': 'Amerikanische Jungferninseln',
  'Wallis and Futuna': 'Wallis und Futuna',
  'Yemen': 'Jemen',
  'South Africa': 'Südafrika',
  'Zambia': 'Sambia',
  'Zimbabwe': 'Simbabwe',
};

/// Der Ländername zur Anzeige, ausgehend von dem, was in der Aufnahme
/// steht.
///
/// Gibt für `null` und Leeres einen leeren Text zurück, damit die
/// Aufrufer keine Sonderfälle brauchen. Alles Unbekannte kommt
/// unverändert wieder – auch Regionen und Städte, die versehentlich hier
/// hereingereicht werden.
String landAnzeige(String? englisch, String sprache) {
  if (englisch == null || englisch.isEmpty) return '';
  if (!sprache.startsWith('de')) return englisch;
  return _laendernamenDeNachEnglisch[englisch] ?? englisch;
}
